name: auto-tags
description: Automaticlly increase your version according to your changes
author: tklein1801
branding:
  icon: 'tag'
  color: 'black'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  package_root:
    description: Programm will look there for the package.json
    required: false
    default: './'
  dry_run:
    description: If you want to test the results and dont wanna post the results
    required: false
    default: false
  # update_version_files:
  #   description: If you want to automaticly update the package.json & package-lock.json
  #   required: false
  #   default: false
outputs:
  tagname:
    description: Fully assembled tag-name
  version:
    description: Raw version
